name: test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2025.4.0
          install: true
          cache: true
      - run: shellcheck bin/setup
      - run: black --check bin/minicloud server
      - run: terraform fmt -recursive -check resources/
